# SPDX-FileCopyrightText: 2024 The Forester Project Contributors
#
# SPDX-License-Identifier: CC0-1.0

image: nixos/24.05

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  cache: https://forester.cachix.org/

secrets:
    - d3cd871a-da6f-4ee3-94e9-fe8bc36233cc

sources:
    - https://git.sr.ht/~jonsterling/ocaml-forester


tasks:
    - setup: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            nix-env -iA nixos.jq
            cachix use forester
    - build: |
            cd ocaml-forester
            nix develop --command dune runtest
            nix build --json \
              | jq -r '.[].outputs | to_entries[].value' \
              | cachix push forester

artifacts:
    - ocaml-forester/result/bin/forester

triggers:
    - action: email
      condition: always
      to: kentookura@gmail.com
